@baseUrl = http://localhost:5000


@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjowLCJpZCI6NiwiaWF0IjoxNjMyODA5MjYwLCJleHAiOjE2MzI4OTU2NjB9.jkEwFkRbxHavlCvZDdiXkZeHljKLcTHlJlF8nzic_2E
@adminToken =  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjowLCJpZCI6NDYsImlhdCI6MTYzMzQ0MzAyMCwiZXhwIjoxNjMzNDU3NDIwfQ.TMfI4brXBYM7HK8zO-kMrb6VJUso61gjN5hdpMqN7Mc


### Login 
POST  {{baseUrl}}/login
Content-Type: application/json
{
    "email": "example@gmail.com",
    "password": "password"
}

### Remove organization from manager (admin route) 
POST  {{baseUrl}}/organization/remove-manager/6?organizationIds=1,2
Content-Type: application/json
Authorization: Bearer {{userToken}}


### Add user to company
POST  {{baseUrl}}admin/manager
Content-Type: application/json
Authorization: Bearer {{adminToken}}
{
    "email": "usichenkokirill@gmail.com",
    "name": "string",
    "type":  "admin", 
}

